export const dataForRag = [
  {
    name: "Hrithik Roshan",
    data: `Hrithik Roshan (pronounced [ɾɪt̪ɪk ɾoʃən];[1] born 10 January 1974) is an Indian actor who works in Hindi cinema. He has portrayed a variety of characters and is known for his dancing skills. One of the highest-paid actors in India, he has won many awards, including six Filmfare Awards, of which four were for Best Actor. Starting from 2012, he has appeared in Forbes India's Celebrity 100 several times based on his income and popularity.

Roshan has frequently collaborated with his father, Rakesh Roshan. He made brief appearances as a child actor in several films in the 1980s and later worked as an assistant director on four of his father's films. His first leading role was in the box-office success Kaho Naa... Pyaar Hai (2000), for which he received several awards. Performances in the 2000 terrorism drama Fiza and the 2001 ensemble family drama Kabhi Khushi Kabhie Gham... consolidated his reputation but were followed by several poorly received films.

The 2003 science fiction film Koi... Mil Gaya, for which Roshan won two Filmfare Awards, was a turning point in his film career; he later starred as the titular superhero in its sequels: Krrish (2006) and Krrish 3 (2013). He earned praise for his portrayal of a thief in Dhoom 2 (2006), Mughal emperor Akbar in Jodhaa Akbar (2008) and a quadriplegic in Guzaarish (2010). He achieved further commercial success with the comedy-drama Zindagi Na Milegi Dobara (2011), the revenge drama Agneepath (2012), the biopic Super 30 (2019), and action films directed by Siddharth Anand—Bang Bang! (2014), War (2019) and Fighter (2024).

Roshan has also performed on stage and debuted on television with the dance reality show Just Dance (2011). As a judge on the latter, he became the highest-paid film star on Indian television at that time. He is involved with a number of humanitarian causes, endorses several brands and products and has launched his own clothing line. Roshan was married for fourteen years to Sussanne Khan, with whom he has two children.

Early life and background
Roshan was born on 10 January 1974 in Bombay to the Roshan family, prominent in Hindi cinema.[2] He is of Punjabi and Bengali descent on his paternal side. Hrithik's paternal grandmother Ira Roshan was a Bengali.[3][4][5] His father, film director Rakesh Roshan, is the son of music director Roshanlal Nagrath; his mother, Pinkie, is the daughter of producer and director J. Om Prakash. His uncle, Rajesh, is a music composer.[2] Roshan has an older sister, Sunaina, and was educated at the Bombay Scottish School.[6] Roshan belongs to a Hindu family, though he considers himself more spiritual than religious.[7][8]

Hrithik Roshan photographed with his father, Rakesh Roshan.
Roshan pictured with father Rakesh at the Jagran Film Festival in 2014[9]
Roshan felt isolated as a child; he was born with an extra thumb fused to the one on his right hand, which led some of his peers to avoid him.[10] He has stammered since the age of six; this caused him problems at school, and he feigned injury and illness to avoid oral tests.[11] He was helped by daily speech therapy.[11][12]

Roshan's grandfather, Prakash first brought him on-screen at the age of six in the film Aasha (1980); he danced in a song enacted by Jeetendra, for which Prakash paid him ₹100.[13][14] Roshan made uncredited appearances in various family film projects, including his father's production Aap Ke Deewane (1980). In Prakash's Aas Paas (1981), he appeared in the song "Shehar Main Charcha Hai".[15] The actor's only speaking role during this period came when he was 12; he was seen as Govinda, the title character's adopted son, in Prakash's Bhagwaan Dada (1986).[16][17] Roshan decided that he wanted to be a full-time actor, but his father insisted that he focus on his studies.[17] In his early 20s, he was diagnosed with scoliosis that would not allow him to dance or perform stunts. Initially devastated,[18][19] he eventually decided to become an actor anyway. Around a year after the diagnosis, he took a chance by jogging on a beach when he was caught in a downpour. There was no pain, and becoming more confident, he was able to increase his pace with no adverse effects. Roshan sees this day as "the turning point of [his] life."[18]

Roshan attended Sydenham College, where he took part in dance and music festivals while studying, graduating in commerce.[2] Roshan assisted his father on four films—Khudgarz (1987), King Uncle (1993), Karan Arjun (1995) and Koyla (1997)—while also sweeping the floor and making tea for the crew.[2][20] After pack-up, Roshan would enact Shah Rukh Khan's scenes from Koyla and film himself to make a judgement about his performance as an actor.[21] While he assisted his father, he studied acting under Kishore Namit Kapoor.[22][23]

Film career
Main article: Hrithik Roshan filmography
2000–2002: Debut, success and setback
Roshan was originally scheduled to make his screen debut as a lead actor opposite Preity Zinta in a cancelled film – Shekhar Kapur's Tara Rum Pum Pum.[24] Instead, he starred in his father's romantic drama Kaho Naa... Pyaar Hai (2000) opposite another debutante, Ameesha Patel. Roshan played dual roles: Rohit, an aspiring singer brutally killed after witnessing a murder, and Raj, an NRI who falls in love with Patel's character.[25] To prepare, he trained with the actor Salman Khan to bulk up physically,[26] worked to improve his diction and took lessons in acting, singing, dancing, fencing and riding.[27] With global revenues of ₹800 million (US$9.6 million),[28] Kaho Naa... Pyaar Hai became one of the highest-grossing Indian films of 2000.[29] His performance was acclaimed by critics;[21][30] Suggu Kanchana on Rediff.com wrote, "[Roshan] is good. The ease and style with which he dances, emotes, fights, makes one forget this is his debut film ... He seems to be the most promising among the recent lot of star sons we have been subjected to."[25] For the role, Roshan received Best Male Debut and Best Actor Awards at the annual Filmfare Awards, IIFA Awards, and Zee Cine Awards.[31] He became the first actor to win both Filmfare Best Debut and Best Actor awards the same year.[32] The film established Roshan as a prominent actor in Bollywood.[33] The actor found life hard after his overnight success, particularly the demands on his time.[34]

In his second release, Khalid Mohammed's crime drama Fiza, Roshan played Amaan, an innocent Muslim boy who becomes a terrorist after the 1992–93 Bombay riots.[34] Roshan appeared in the film to expand his horizons as an actor.[35] Co-starring Karisma Kapoor and Jaya Bachchan, Fiza was moderately successful at the box office,[36] and Roshan's performance earned him a second nomination for Best Actor at the Filmfare ceremony.[37] Taran Adarsh of Bollywood Hungama praised him as the production's prime asset, commending his "body language, his diction, his expressions, [and] his overall persona."[38] Roshan next appeared in Vidhu Vinod Chopra's action drama Mission Kashmir (2000) alongside Sanjay Dutt, Preity Zinta, and Jackie Shroff. Set in the valley of Kashmir during the Indo-Pakistani conflicts, the film addressed the topics of terrorism and crime, and was a financial success.[29] Roshan was drawn to his complex role of a young man traumatised by the discovery that his adoptive father had been responsible for the death of his entire birth family.[35] In Adarsh's opinion, Roshan "brightens up the screen with his magnetic presence. His body language, coupled with his expressions, is sure to win him plaudits."[39]

A picture of Hrithik Roshan taken in 2001.
Roshan at an event for Kabhi Khushi Kabhie Gham... (2001)—his biggest commercial success to that point[40]
In 2001, Roshan appeared in two films, the first of which was Subhash Ghai's Yaadein, a romantic drama which paired him with Kareena Kapoor and reunited him with Shroff. Although highly anticipated, Yaadein was reviled by critics; in The Hindu, Ziya Us Salam criticised the director for relying on Roshan's commercial appeal.[41][42] Roshan next had a supporting role in Karan Johar's ensemble melodrama Kabhi Khushi Kabhie Gham... alongside Amitabh Bachchan, Jaya Bachchan, Shah Rukh Khan, Kajol and Kareena Kapoor. He was cast as Rohan Raichand—the younger son of Bachchan's character who plots to reunite him with his adopted son (played by Khan)—after Johar had watched a rough cut of Kaho Naa... Pyaar Hai.[43] Kabhi Khushi Kabhie Gham... finished as India's highest-grossing film of the year,[44] and among the most successful Bollywood films in the overseas market, earning ₹1.36 billion (US$16 million) worldwide.[45] Writing for Rediff.com, Anjum N described Roshan as "the surprise scene-stealer", praising him for holding his own against the established actors.[46] Roshan received a nomination for the Filmfare Award for Best Supporting Actor for his performance.[37]

In 2002 Vikram Bhatt's romance Aap Mujhe Achche Lagne Lage reunited him with Ameesha Patel but failed at the box office, as did Arjun Sablok's romance Na Tum Jaano Na Hum (2002), in which he co-starred with Saif Ali Khan and Esha Deol.[47] Roshan's final role that year was in a Yash Raj Films production, the high-profile Mujhse Dosti Karoge! co-starring Rani Mukerji and Kareena Kapoor. The romantic comedy was heavily promoted before its release and made money internationally, though not in India.[48][49] In another commercial failure, Sooraj R. Barjatya's Main Prem Ki Diwani Hoon, Roshan was cast alongside Kareena Kapoor for the fourth time, and Abhishek Bachchan. The press labelled Roshan a "one-trick pony" and suggested that the failure of these films would end his career.[41][50]

2003–2008: Revival and awards success

Roshan (second from left) at the launch of Koi... Mil Gaya (2003)
Roshan's career began to revive with a starring role in Koi... Mil Gaya (2003).[21][51] The film, directed and produced by his father, centers on his character Rohit Mehra, a developmentally disabled young man, who comes in contact with an extraterrestrial being—a role that required him to lose nearly 8 kilograms (18 lb). Roshan recalls the experience of starring in the film fondly: "I could live my childhood [again]. I could eat as many chocolates as I wanted. I became a baby and everybody was so caring towards me."[52] In the book Film Sequels, Carolyn Jess-Cooke drew similarities between the character and Forrest Gump, portrayed by Tom Hanks in the titular film, but this idea was dismissed by Roshan.[52][53] Film critics were polarised on their view of the film—some of them negatively compared its storyline to the 1982 Hollywood release E.T. the Extra-Terrestrial—but were unanimous in their praise for Roshan.[18][54] In a 2010 retrospective of the Top 80 Iconic Performances of Bollywood, Filmfare noted "how flesh and blood Hrithik's act is. Simply because he believes he is the part. Watch him laugh, cry or bond with his remote controlled alien friend and note his nuanced turn."[55] A Rediff.com critic agreed that Roshan was "the turbojet that propels the film to the realm of the extraordinary."[56] Koi... Mil Gaya was one of the most popular Bollywood films of the year, earning ₹823.3 million (US$9.9 million) worldwide and Roshan won both Filmfare Awards for Best Actor and Best Actor (Critics).[37][57]

"I am glad I have the intelligence to understand what is happening to me. If I allow myself to get affected by all this hype, I'll stunt my growth as an actor and be damned for life. I know that I still have a long way to go before I can even aspire to equal the achievements of any of the superstars. I know I am good at my job, and I am sure I will be damn good one day but right now, I also know how bad I can be."

—Roshan on his position as a popular Bollywood actor[8]

The following year, Roshan collaborated with Amitabh Bachchan and Preity Zinta on Farhan Akhtar's Lakshya (2004), a fictionalised coming-of-age story set against events from the 1999 Kargil War. He also featured in the item number "Main Aisa Kyun Hoon" (choreographed by Prabhu Deva) which proved popular with audiences.[58] Roshan found it "one of the most challenging films" of his career at the time and said it made him respect soldiers.[59] Although trade journalists expected the film to do well commercially,[59] it failed to attract a wide audience. Over the years, it has attained a cult status in India.[60] For the film, Roshan earned Best Actor nominations at the Filmfare and Zee Cine ceremony.[37][61] Manish Gajjar of the BBC praised Roshan's versatility and his transformation from a carefree youth to a determined and courageous soldier.[62] Reviewing the film in 2016, Tatsam Mukherjee of India Today described his performance as career-best, highlighting his scene before the climax.[60]

Roshan was not seen on screen again until 2006, with three new releases, including a cameo at the end of the year in the romance I See You.[63] He co-starred with Naseeruddin Shah and Priyanka Chopra in his father's superhero production Krrish. A follow-up to his family's production Koi... Mil Gaya, it saw him play dual roles—the title superhero and his character from the original film. Before production, Roshan travelled to China to train with Tony Ching for the cable work that would be needed to make his character fly.[64] Among the several injuries he sustained during production, Roshan tore the hamstring in his right leg and broke his thumb and toe.[65] Krrish became the third-highest-grossing Bollywood film of 2006 with a worldwide revenue of ₹1.26 billion (US$15 million).[66] It garnered him Best Actor awards at the 2007 Screen and the International Indian Film Academy Awards.[37] Ronnie Scheib of Variety considered Roshan a prime asset of the film, noting that he "pulls off the pic's wilder absurdities with considerable panache."[67]

For his role as an enigmatic master thief in Dhoom 2 (2006)—an action sequel co-starring Aishwarya Rai, Bipasha Basu and Abhishek Bachchan—Roshan won his third Filmfare Award for Best Actor.[37] The film critic Rajeev Masand called him "the heart, the soul, and the spirit of the film", and praised his stunts, concluding that he "holds the film together and even manages to take your attention away from its many flaws".[68] Bored by playing the "good guy", Roshan was excited to play an anti-hero who lacks heroic attributes, for the first time.[64] At the request of the film's producer Aditya Chopra, Roshan lost 12 pounds (5.4 kg) for the role;[69] he also learnt skateboarding, snow boarding, rollerblading and sand surfing.[70][71] With earnings of ₹1.5 billion (US$18 million), Dhoom 2 became the highest grossing Indian film at that time, a distinction that was held for two years.[72] In the 2007 melodrama Om Shanti Om, he made a cameo alongside several Bollywood stars.[63]

In 2008, Roshan was cast in Ashutosh Gowariker's Jodhaa Akbar, a partly fictionalised account of a marriage of convenience between the Mughal emperor Akbar (played by Roshan) and the Rajput princess Jodha Bai (played by Rai). Gowariker believed Roshan possessed the regal bearing and physique required to play the role of a king.[73] For the role, Roshan learned sword-fighting and horse-riding, and also took Urdu lessons.[74][75] Jodhaa Akbar earned ₹1.2 billion (US$14 million) worldwide.[72] Roshan's performance earned him his fourth Filmfare Best Actor Award.[37] Critics were generally appreciative of Roshan's performance.[18] Raja Sen of Rediff.com thought that Roshan "proves a very good Akbar. There are times when his inflection seems too modern, but the actor gives the performance his all, slipping into the skin of the character and staying there."[76] Roshan ended 2008 with an appearance in the popular item number "Krazzy 4" from the film of same name.[77]

2009–2012: Critical acclaim
Following a small role in Zoya Akhtar's Luck by Chance in 2009, Roshan starred in and recorded "Kites in the Sky" for the multi-national romantic thriller Kites (2010).[78] In the film, produced by his father, he played a man running a green card scam in Las Vegas in which he has married 11 different women in exchange for money. Kites opened on a record-breaking 3000 screens, and became the first Bollywood film to break into the North American top 10.[79] However, the film eventually underperformed at India's box office and received negative reviews from critics.[80] The website Box Office India attributed this failure to its multilingual dialogues.[81] In a review for Rediff.com, Matthew Schneeberger thought that Roshan "overacts. A lot. In Kites, he nails a few scenes, but bungles many more, particularly the film's catastrophically bad ending."[82]

Hrithik Roshan and Aishwarya Rai are looking away from the camera.
Roshan with co-star Aishwarya Rai promoting Guzaarish. A popular on-screen couple, they also starred together in Dhoom 2 and Jodhaa Akbar.[83]
Roshan then collaborated with director Sanjay Leela Bhansali on the drama Guzaarish (2010) in which he had the role of Ethan Mascarenhas, a former magician suffering from quadriplegia, who after years of struggle, files an appeal for euthanasia. Roshan had reservations about the role but agreed to the project after reading the film's story.[84] To understand his role better, he interacted with paraplegic patients.[14] In his own words, "I used to spend six hours with the patients, initially once a week and then once a month. I used to go to understand what they go through, what they think, what their needs are. They have taught me a lot of things."[85] He also trained with a Ukrainian magician to perform the film's magic stunts, and put on weight to look the part.[86][87] The film failed at the box office, though it and Roshan's performance were positively received by critics.[18][80] A writer for Zee News praised the chemistry between Roshan and Rai, adding that they "break the Bollywood mould of stereotypes."[88] Roshan received the Zee Cine Award for Best Actor (Critics) and nominations for Filmfare, IIFA and Zee Cine Award for Best Actor.[37]

In 2011, Roshan appeared in Zoya Akhtar's ensemble comedy-drama Zindagi Na Milegi Dobara alongside Abhay Deol and Farhan Akhtar as three friends who embark on a bachelor trip where they overcome their insecurities. Zoya cast Roshan in the role of an uptight workaholic as she considers him her favourite actor.[89] For the film's soundtrack, Roshan recorded the song "Señorita" with his co-stars and María del Mar Fernández.[78] Zindagi Na Milegi Dobara was released to positive reviews and Roshan's performance was praised.[90] Rajeev Masand wrote, "Hrithik Roshan once again brings real depth to his character with a spectacular performance. He's shy and restrained, then lets go with such fantastic intensity that you make the inward journey with his character."[91] The film grossed ₹1.53 billion (US$18 million) worldwide and became Roshan's first commercial success in three years.[72] Later that year, he made a special appearance in Farhan's Don 2.[92]

Roshan's only screen appearance in 2012 was in Karan Malhotra's Agneepath, a retelling of the 1990 film of the same name. Cast alongside Rishi Kapoor, Sanjay Dutt and Priyanka Chopra, Roshan reinterpreted the character Vijay Deenanath Chauhan (originally played by Amitabh Bachchan), a common man who seeks revenge against an unscrupulous man for framing and murdering his father. Roshan was initially sceptical of taking up a role earlier played by Bachchan, and thought hard before accepting.[93] He did not watch the original film for inspiration as he found his role to be completely different.[94] In one of several accidents to happen during production, Roshan suffered a painful back injury. He deemed Agneepath "the hardest [project] I've ever worked in my life" owing to the exhaustion he felt while filming.[95] The film broke Bollywood's highest opening-day earnings record, and had a worldwide gross of ₹1.93 billion (US$23 million).[96][97] A Firstpost reviewer thought Roshan "breathes fire and soul into Agneepath".[98] The actor received a third consecutive Stardust Award for Best Actor in a Drama, having won previously for Guzaarish and Zindagi Na Milegi Dobara.[99][100]

2013–present: Commercial success with limited work
Roshan appeared in the third instalment of the Krrish film series—Krrish 3 (2013) which also starred Priyanka Chopra, Vivek Oberoi and Kangana Ranaut. During production, Roshan was injured when he fell down, which resulted in back pain.[101][102] Critics thought that the film was entertaining but lacking in originality, though Roshan's performance garnered praise.[103] The editor Komal Nahta lauded Roshan for playing three different characters in the film.[104] Krrish 3 grossed ₹3.93 billion (US$47 million) worldwide, becoming one of the highest-grossing Indian films of all time.[105] Roshan received a fourth and fifth consecutive Filmfare nomination for his performances in Krrish 3,[106] and the 2014 action comedy Bang Bang!, a remake of the 2010 Hollywood release Knight and Day and one of the most expensive Bollywood films.[107][108] Playing the role of an eccentric secret agent who plots to track down a terrorist, Roshan became the first actor to perform a flyboarding stunt in film.[109] While filming in Thailand, Roshan suffered a head injury from a stunt accident and underwent brain surgery at the Hinduja Hospital performed by Dr. B. K. Misra to relieve subacute-subdural hematoma.[110] Writing for Bollywood news website Koimoi, critic Mohar Basu noted that Roshan was "pitch perfect" and "breez[ed] through his part brilliantly."[111] The film earned ₹3.4 billion (US$41 million) in global ticket sales, making it among the highest-grossing Indian films.[112]

Hrithik Roshan is looking towards the camera.
Roshan at a promotional event for Mohenjo Daro in 2016
For playing the role of a farmer in 2016 BC who travels to Mohenjo-daro in Ashutosh Gowariker's Mohenjo Daro (2016), Roshan was paid ₹500 million (US$6.0 million), a record-breaking remuneration for an Indian actor.[113] He underwent a three-month training to achieve the "lithe" and "agile" physique required for his role.[114] Despite being a highly anticipated release, it failed commercially, and critics were generally unenthusiastic.[115] Dismissing the film as an "unintentional comedy", Anupama Chopra wrote that Roshan "pours his soul into every scene. But the burden of carrying this leaden, cartoon-like narrative proves too much even for his Herculean shoulders."[116] Roshan was next seen alongside Yami Gautam in Sanjay Gupta's Kaabil (2017), a romantic thriller about a blind man who avenges the rape of his blind wife. To ensure authenticity in his portrayal, Roshan locked himself in a room for four days and avoided contact with people.[117] Reviews for the film were generally positive with particular praise for Roshan's performance.[118] Meena Iyer of The Times of India found his performance to be his best to date,[119] and Shubhra Gupta on The Indian Express considered him "the only bright spot in this dispirited mess of a movie."[120] The film accumulated ₹1.96 billion (US$23 million) worldwide.[121]

After two years of screen absence, Roshan starred in two films in 2019, first in Vikas Bahl's biographical film Super 30, based on the mathematician Anand Kumar and his eponymous educational program. For the role, Roshan hired a trainer from Bhagalpur to learn Bihari accent.[122] The film was released to mixed reviews but was a commercial success, grossing ₹2 billion (US$24 million) worldwide.[123][124] While NDTV's Saibal Chatterjee found Roshan miscast in his role,[125] Michael Gomes of Khaleej Times called it one of his best performances.[126] Roshan found his biggest commercial success in the highest-grossing Bollywood film of 2019, the ₹4.75 billion (US$57 million)-earning action thriller War.[127][128] The film, Roshan's first with Yash Raj Films since Dhoom 2, tells the story of an Indian soldier (Tiger Shroff) tasked with eliminating his former mentor (Roshan) who has gone rogue. Reviews for the film and the performances were positive; Rajeev Masand praised Roshan and Shroff for their commitment to the action, "bringing swag to the big stylish sequences and a visceral energy to the one-on-one punch-ups in the movie".[129]

Roshan's next release was three years later in Vikram Vedha (2022), a remake of the Tamil film of the same name.[130][131] The film tells the story of Vikram, a police inspector (Saif Ali Khan) who sets out to track down and kill Vedha (Roshan), a gangster. It received positive reviews from critics.[132] Rachana Dubey of The Times of India praised Roshan's performance, writing that he "is menacing, ruthless and extremely emotional in parts".[133] The film did not perform well commercially, leading Roshan to question the kind of roles he would do in the future.[134] Roshan starred in Siddharth Anand's action film Fighter (2024), with Deepika Padukone and Anil Kapoor.[135] For their roles as Indian Air Force officers, Roshan and Padukone underwent martial arts training.[136] Ganesh Aaglave of Firstpost praised the emotional depth of Roshan's performance and his dialogue delivery.[137] It emerged as a modest commercial success.[138] He will next lead the sequel War 2 set in the YRF Spy Universe.[139]

Other work
Roshan has performed on stage, appeared on television, and launched a clothing line. His first tour (Heartthrobs: Live in Concert (2002) with Kareena Kapoor, Karisma Kapoor, Arjun Rampal and Aftab Shivdasani) was successful in the United States and Canada.[140][141] At the end of that year, he danced on stage with Amitabh Bachchan, Sanjay Dutt, Kareena Kapoor, Rani Mukerji and Shah Rukh Khan at Kings Park Stadium in Durban, South Africa in the show Now or Never.[142] In 2011, Roshan served as a judge alongside Farah Khan and Vaibhavi Merchant for the dance competition reality show, Just Dance. He became the highest-paid film star on Indian television after he was paid ₹20 million (US$240,000) per episode. The show ran from June to October 2011.[143] In November 2013, Roshan launched his clothing line, the casual wear brand HRx.[144]


Roshan at a charity football match in 2014
Roshan is vocal about his childhood stammer.[145] He actively supports the Dilkhush Special School for mentally challenged children in Mumbai.[146] In 2008, he donated ₹2 million (US$24,000) to the Nanavati Hospital for the treatment of stammering children.[12] Roshan set up a charity foundation in 2009 that aims to work for handicapped people.[147] He donates roughly ₹700,000 (US$8,400) for charity every month,[148] and believes that people should publicise their philanthropic work to set an example for others.[146] In 2013, he took part in a festivity at Ghatkopar, whose proceeds went to an NGO supporting tribal girls suffering from malnutrition and starvation.[149] Also that year, he donated ₹2.5 million (US$30,000) to help the victims of the 2013 North India floods.[150]

Alongside other Bollywood stars, Roshan played a football match for charity organised by Aamir Khan's daughter, Ira, in 2014.[151] The following year, he appeared with Sonam Kapoor in the music video for "Dheere Dheere", whose profits were donated to charity.[152] Later that year, Roshan became the Indian brand ambassador for UNICEF and the Global Goals campaign's World's Largest Lesson that aims to educate children in over 100 countries about the Sustainable Development Goals.[153] In 2016, Roshan and other Bollywood actors made donations for building homes for families affected by the 2015 South Indian floods.[154]

Following his debut film, Roshan signed on for endorsement deals with Coca-Cola, Tamarind and Hero Honda, all for three years and for at least ₹30 million (US$360,000).[41] As of 2010, he is celebrity endorser for such brands and products as Provogue, Parle Hide and Seek, Reliance Communications and Hero Honda and recently roshan has completed six years with Rado.[155][156] The Times of India reported that Roshan received ₹12 million (US$140,000) to ₹15 million (US$180,000) for each endorsement, making him one of the highest-paid male celebrity endorsers.[157] In 2016, Duff & Phelps estimated his brand value to be US$34.1 million, the eighth highest of Indian celebrities.[158] In 2017, Roshan was signed as the brand ambassador of a Health and wellness startup Cure.fit and is touted as one of the largest endorsement deal signed by an Indian startup.[159]

Personal life
Hrithik Roshan with his wife, Sussanne Khan.
Roshan and Sussanne Khan (pictured in 2012) were married for fourteen years
On 20 December 2000, Roshan married Sussanne Khan in a private ceremony in Bangalore.[160] Despite their religious difference—Roshan is a Hindu and Khan is a Muslim—Roshan says that he equally valued her beliefs.[7] The couple has two sons, Hrehaan (born in 2006) and Hridhaan (born in 2008).[161][162] Roshan and Sussanne separated in December 2013 and their divorce was finalised in November 2014.[160] Both maintained that they parted amicably.[163]

In 2016 Roshan had filed a lawsuit against Krrish 3 co-star Kangana Ranaut for cyber stalking and harassment. Denying the charges, Ranaut filed a counter-charge claiming that his lawsuit was an attempt to cover up an affair.[164] Owing to a lack of evidence, the Mumbai Police closed the case later that year.[165] As of 2023, Roshan is dating actress Saba Azad.[166]

Roshan had considered quitting the film industry after two assailants fired bullets at his father in 2000.[27] Later that December, he was involved in a controversy when Nepalese newspapers and Jamim Shah's Channel Nepal accused him of stating in a Star Plus interview that he hated Nepal and its people. This led to protests in the country, a ban on screening of his films, and four people's deaths after street violence.[167] Nepalese people threatened to "bury [him] alive" if he ever visited the country.[168] Star Plus, for its part, stated that Roshan "did not touch upon Nepal." The violence calmed down after Roshan wrote a two-page rejoinder in which he denied having made any claim against the country. Nepali actress Manisha Koirala helped distribute it to newspapers and a local television station.[169]

Artistry and media image
As the son of the filmmaker Rakesh, Roshan faced the media spotlight from a young age.[22] Discussing nepotism in Bollywood, Shama Rana views him as one of several actors who managed film careers with the help of family relations in the industry.[170] On the other hand, Roshan is acknowledged in the media for his devotion to his work and for his ability to commit heavily to each role.[14][171] He insists on learning any necessary skills and performing stunts himself,[172][173] and is particularly known for his professionalism.[174] The director Ashutosh Gowariker praised Roshan when he continued filming Mohenjo Daro despite several injuries and being in a troubled state of mind.[175] Zoya Akhtar, who considers Roshan her favourite actor, and directed him in Zindagi Na Milegi Dobara, remarks on his ability to display a range of emotions on screen.[18][89]

Roshan in a t-shirt
Roshan is frequently cited as a sex symbol and a style icon by the Indian media
In an attempt to avoid typecasting, Roshan takes on diverse parts.[18][35] He looks at the scripts as a platform to inspire with the strength and courage of his characters and to make his audiences smile.[18] Roshan was noted by critics for his versatility in portraying a variety of characters in Koi... Mil Gaya (2003), Lakshya (2004), Jodhaa Akbar (2008), and Guzaarish (2010).[18] Box Office India ranked him first on its top actors listing in 2000 and later included him in 2003, 2004, 2006 and 2007.[176] Roshan topped Rediff.com's list of best Bollywood actors in 2003,[21] and was ranked fourth in 2006.[177] Filmfare magazine included two of his performances—from Koi... Mil Gaya and Lakshya—on its 2010 list of 80 Iconic Performances.[55][178] In March 2011, Roshan placed fourth on Rediff.com's list of Top 10 Actors of 2000–2010.[179]

Roshan's dancing ability has drawn praise from the media, an opinion he disagrees with.[18][180] The Los Angeles Times finds him to be "a sensational dancer" who "has the dashing, chiseled looks of a silent movie matinee idol."[181] Although author Nandana Bose attributed Roshan's popularity to Bollywood's preoccupation with traditional hypermasculinity, she wrote that he sets himself apart by showcasing dancing talent and "transnational, transfigurative corporeality". According to Bose, Roshan's stardom is marked by his ability to seamlessly transition between roles, from dancing star to credible superhero, shaping the industry's landscape.[182] Some critics believe that he is only able to dance and act in his father's films.[183] Sanya Panwar of Hindustan Times criticised his inclination towards "glamorous, albeit empty" and stereotypical parts.[184]

Roshan has established himself as a sex symbol and a style icon in India.[185][186][187] In 2006, Roshan was one of the four Bollywood actors, along with Priyanka Chopra, Kajol and Shah Rukh Khan, whose miniature dolls were launched in the United Kingdom, under the name of "Bollywood Legends".[188] He topped The Times of India's listing of 50 Most Desirable Men in 2010 and ranked among the top five for the next five years.[189] In 2010 and 2012, the Indian edition of GQ included him in their listing of Bollywood's best dressed men.[190][191] A life-size, wax figure of him was installed at London's Madame Tussauds museum in January 2011, making him the fifth Indian actor to have been replicated as a wax statue there.[192] Versions of the statue were installed at Madame Tussauds' museums in New York, Washington and other cities in the world.[193] Roshan regularly features in the magazine Eastern Eye's listing of the 50 Sexiest Asian Men. He topped the list in 2011, 2012 and 2014, and featured among the top five in 2010, 2013 and 2015 to 2018.[194]

Roshan is among Bollywood's highest-paid actors.[113] Discussing his success ratio at the box office in a 2014 article, Daily News and Analysis credited him as "the most bankable star" in Bollywood.[195] He was named the second most powerful Indian film star by Forbes in 2001.[196] He ranked fourth in Filmfare Power List in 2007.[197] In a 2009 poll conducted by Daily News and Analysis Roshan was voted one of India's most popular icons.[198] At the 2009 FICCI-IIFA Awards, Roshan was one of the ten recipients of the most powerful Bollywood entertainers of the 2000s.[199] From 2012 to 2019, Roshan was placed on Forbes India's Celebrity 100—a list based on the income and popularity of Indian celebrities—peaking at ninth position in 2014 with an annual income of ₹850 million (US$10 million).[200][201]`,
  },
  {
    name: "Tom Cruise",
    data: `Thomas Cruise Mapother IV (born July 3, 1962) is an American actor and producer. Regarded as a Hollywood icon,[1][2][3] he has received various accolades, including an Honorary Palme d'Or and three Golden Globe Awards, in addition to nominations for four Academy Awards. His films have grossed over $5 billion in North America and over $12 billion worldwide,[4] placing him among the highest-grossing actors of all time.[5] Cruise holds the Guinness World Record for the most consecutive $100-million-grossing movies, a feat that was achieved during the period of 2012 to 2018.[6] One of the most bankable stars, he is consistently one of the world's highest-paid actors.[7]

Cruise began acting in the early 1980s and made his breakthrough with leading roles in the comedy Risky Business (1983) and the action film Top Gun (1986). Critical acclaim came with his roles in the dramas The Color of Money (1986), Rain Man (1988), and Born on the Fourth of July (1989). For his portrayal of Ron Kovic in the latter, he won a Golden Globe Award and received a nomination for the Academy Award for Best Actor. As a leading Hollywood star in the 1990s, he starred in commercially successful films, including the drama A Few Good Men (1992), the thriller The Firm (1993), the horror film Interview with the Vampire (1994), and the romance Jerry Maguire (1996). For the latter, he won a Golden Globe Award for Best Actor and received a second Academy Award nomination. Cruise's performance as a motivational speaker in the drama Magnolia (1999) earned him another Golden Globe Award and a nomination for the Academy Award for Best Supporting Actor.

Cruise subsequently established himself as a star of science fiction and action films, often performing his own risky stunts. He has played fictional agent Ethan Hunt in the Mission: Impossible film series since 1996. His other films in the genre include Vanilla Sky (2001), Minority Report (2002), The Last Samurai (2003), Collateral (2004), War of the Worlds (2005), Knight and Day (2010), Jack Reacher (2012), Oblivion (2013), Edge of Tomorrow (2014), and Top Gun: Maverick (2022).

Cruise received a star on the Hollywood Walk of Fame in 1986. He was named People's Sexiest Man Alive in 1990,[8] and received the top honor of "Most Beautiful People" in 1997.[9] He is an outspoken advocate for the Church of Scientology, which he credits with helping him overcome dyslexia.

Early life and education
Cruise was born on July 3, 1962, in Syracuse, New York,[10] to electrical engineer Thomas Cruise Mapother III (1934–1984) and special education teacher Mary Lee (née Pfeiffer; 1936–2017).[11] His parents were both from Louisville, Kentucky,[12] and had English, German, and Irish ancestry.[13][14] Cruise has three sisters named Lee Anne, Marian, and Cass. One of his cousins, William Mapother, is also an actor who has appeared alongside Cruise in five films.[15] Cruise grew up in near poverty and had a Catholic upbringing. He later described his father as "a merchant of chaos",[16] a "bully", and a "coward" who beat his children. He elaborated, "[My father] was the kind of person where, if something goes wrong, they kick you. It was a great lesson in my life—how he'd lull you in, make you feel safe and then, bang! For me, it was like, 'There's something wrong with this guy. Don't trust him. Be careful around him.'"[16] Cruise's biological father died of cancer in 1984.[17]

In total, Cruise attended 15 schools in 14 years.[18] Cruise spent part of his childhood in Canada; when his father took a job as a defense consultant with the Canadian Armed Forces, his family moved in late 1971 to Beacon Hill, Ottawa.[19] He attended the new Robert Hopkins Public School for his fourth and fifth grade education.[19][20] He first became involved in drama in fourth grade, under drama teacher George Steinburg. He and six other boys put on an improvised play to music called IT at the Carleton Elementary School drama festival.[19] Drama organizer Val Wright was in the audience and later said that "the movement and improvisation were excellent ... a classic ensemble piece."[19]

In sixth grade, Cruise went to Henry Munro Middle School in Ottawa. That year, his mother left his father, taking Cruise and his sisters back to the United States.[19] In 1978, she married Jack South.[21] Cruise briefly took a Catholic church scholarship and attended the St. Francis Seminary in Cincinnati; he aspired to become a Franciscan priest before leaving after a year. Priests at the seminary have said Cruise chose to leave the school when his family relocated again; however, a former classmate said that they were both asked to leave after getting caught taking liquor.[22][23]: 24–26  In his senior year of high school, he played football for the varsity team as a linebacker, but was cut from the squad after getting caught drinking beer before a game.[23]: 47  He went on to star in the school's production of Guys and Dolls.[24] In 1980, he graduated from Glen Ridge High School in Glen Ridge, New Jersey.[25]

Acting career

Cruise in 1985 at a reception hosted by First Lady Nancy Reagan at the White House
1980s: Breakthrough and stardom
At age 18,[26] with the blessing of his mother and stepfather, Cruise moved to New York City to pursue an acting career.[24] After working as a busboy in New York, he went to Los Angeles to try out for television roles. He signed with CAA and began acting in films.[26] He made his film debut in a bit part in the 1981 film Endless Love, followed by a major supporting role as a crazed military academy student in Taps later that year. Cruise was originally supposed to appear as a background actor but his role was expanded after impressing director Harold Becker.[27] In 1983, Cruise was part of the ensemble cast of Francis Ford Coppola's The Outsiders. That same year he appeared in All the Right Moves and Risky Business, which has been described as "A Generation X classic, and a career maker for Tom Cruise."[28] He also played the male lead in the Ridley Scott film Legend, released in 1985.[29] By 1986's Top Gun, his status as a superstar had been cemented.[30]


Tom Cruise at the 61st Academy Awards in 1989
Cruise followed up Top Gun with Martin Scorsese's The Color of Money (1986), which came out the same year, and which paired him with Paul Newman. Their chemistry won praise among critics with The Washington Post writing, "One of the subtle achievements of both Cruise's and Newman's performances is that you feel that both of them are genuinely top-notch pool hustlers".[31] In 1988, Cruise starred in Cocktail, a film that was a box office success but failed with critics. His performance earned him a nomination for the Razzie Award for Worst Actor. Later that year he starred with Dustin Hoffman in Barry Levinson's Rain Man, which won the Academy Award for Best Film and Cruise the Kansas City Film Critics Circle Award for Best Supporting Actor.[citation needed]

In 1989, Cruise portrayed real-life paralyzed Vietnam War veteran Ron Kovic in Oliver Stone's war epic Born on the Fourth of July. Film critic Roger Ebert of the Chicago Sun-Times wrote, "Nothing Cruise has done will prepare you for what he does in Born on the Fourth of July ... His performance is so good that the movie lives through it. Stone is able to make his statement with Cruise's face and voice and doesn't need to put everything into the dialogue."[32] The performance earned him a Golden Globe Award for Best Actor – Motion Picture Drama, the Chicago Film Critics Association Award for Best Actor, the People's Choice Award for Favorite Motion Picture Actor, a nomination for BAFTA Award for Best Actor in a Leading Role, and Cruise's first Best Actor Academy Award nomination.[citation needed]

1990s: Dramatic roles
Cruise's next films were Days of Thunder (1990) and Far and Away (1992), both of which co-starred then-wife Nicole Kidman as his love interest, followed by the legal thriller The Firm, which was a critical and commercial success. In 1994, Cruise starred along with Brad Pitt, Antonio Banderas and Christian Slater in Neil Jordan's Interview with the Vampire, a gothic drama/horror film that was based on Anne Rice's best-selling novel. The film was well-received, although Rice was initially quite outspoken in her criticism of Cruise having been cast in the film, as Julian Sands was her first choice. Upon seeing the film, however, she paid $7,740 (equivalent to $15,911 in 2023) for a two-page ad in Daily Variety praising his performance and apologizing for her previous doubts about him.[33]

In 1996, Cruise starred as superspy Ethan Hunt in the reboot of Mission: Impossible, which he also produced. The film was directed by Brian De Palma and was a box office success, although it received criticism regarding the Jim Phelps character being a villain despite being a protagonist of the original television series.[34] Film critic Stephen Holden of The New York Times praised Cruise's performance, declaring "Tom Cruise has found the perfect superhero character on which to graft his breathlessly gung-ho screen personality."[35] In the same year, Cruise took on the title role in Cameron Crowe's sports drama Jerry Maguire playing a sports agent in search of love. He stars opposite Renee Zellweger, and Cuba Gooding Jr. The film was a massive financial success with Cruise earning a Golden Globe Award for Best Actor – Motion Picture Musical or Comedy and his second nomination for an Academy Award for Best Actor.[citation needed]

In 1999, Cruise costarred with Kidman in Stanley Kubrick's erotic and psychological drama film Eyes Wide Shut. Peter Bradshaw of The Guardian praised both Cruise and Kidman on their performances writing, "Cruise in particular lays himself open in that fiercely committed way that he tries everything as an actor".[36] That same year he took a rare supporting role, as a motivational speaker, Frank T.J. Mackey, in Paul Thomas Anderson's Magnolia (1999). Rolling Stone film critic Peter Travers heaped praise on Cruise writing, "Cruise is a revelation, fully deserving of the shower of superlatives coming his way ... Cruise seethes with the chaotic energy of a wounded animal – he's devastating."[37] For his performance he received another Golden Globe and nomination for an Academy Award.[citation needed]

2000s: Established career
In 2000, Cruise returned as Ethan Hunt in the second installment of the Mission Impossible films, Mission: Impossible 2. The film was helmed by Hong Kong director John Woo and branded with his gun fu style; it continued the series' success at the box office, taking in $547 million worldwide.[38] Unlike its predecessor, it was the highest-grossing film of the year,[39] but had a mixed critical reception.[40] Cruise received an MTV Movie Award for Best Male Performance for the film.[41]

His next five films were major critical and commercial successes.[42][43] The following year, Cruise starred in the romantic thriller Vanilla Sky (2001) with Cameron Diaz and Penélope Cruz. In 2002, Cruise starred in the dystopian science fiction action film Minority Report, which was directed by Steven Spielberg and based on the science fiction short story by Philip K. Dick.


Cruise at the 2007 London Film Festival for the premiere of Lions for Lambs
In 2003, he starred in Edward Zwick's period action drama The Last Samurai, for which he received a Golden Globe nomination for best actor.[44] In 2004, Cruise received critical acclaim for his performance as Vincent in Collateral. The critical consensus states that "Driven by director Michael Mann's trademark visuals and a lean, villainous performance from Tom Cruise, Collateral is a stylish and compelling noir thriller."[45] In 2005, Cruise worked again with Steven Spielberg in War of the Worlds, a loose adaptation of the H. G. Wells novel of the same name, which became the fourth highest-grossing film of the year with US$591.4 million worldwide.[46] Also in 2005, he was a nominee for the People's Choice Award for Favorite Male Movie Star[47] and the winner of the MTV Generation Award.[48] Cruise was nominated for seven Saturn Awards between 2002 and 2009, winning once. Nine of the ten films he starred in during the decade made over $100 million at the box office.[42]

In 2006, he returned to his role as Ethan Hunt in the third installment of the Mission Impossible film series, Mission: Impossible III. The film was more positively received by critics than the previous films in the series and grossed nearly $400 million at the box office.[49] In 2007, Cruise took a rare supporting role for the second time in Lions for Lambs, which was a commercial disappointment. This was followed by an unrecognizable appearance as "Les Grossman" in the 2008 comedy Tropic Thunder with Ben Stiller, Jack Black, and Robert Downey Jr. This performance earned Cruise a Golden Globe nomination.[44] Cruise played the central role in the historical thriller Valkyrie released on December 25, 2008, to box office success.[50]

2010s: Action star
In March 2010, Cruise completed filming the action-comedy Knight and Day, in which he re-teamed with former costar Cameron Diaz; the film was released on June 23, 2010.[51] On February 9, 2010, Cruise confirmed that he would star in Mission: Impossible – Ghost Protocol, the fourth installment in the Mission: Impossible series. The film was released in December 2011[52] to high critical acclaim[53] and box office success.[54] Unadjusted for ticket price inflation, it was Cruise's biggest commercial success to that date.[55]


Cruise at the 2013 San Diego Comic Con
On May 6, 2011, Cruise was awarded a humanitarian award from the Simon Wiesenthal Center and its Museum of Tolerance for his work as a dedicated philanthropist.[56] In mid-2011, Cruise started shooting the movie Rock of Ages (2012), in which he played the fictional character Stacee Jaxx. The film was released in June 2012 and was a rare box-office misstep for Cruise.[57] Cruise however received positive reviews for his performance with Variety's film critic Justin Chang writing, "Channeling the likes of Axl Rose and Keith Richards with his tattoos, heavy furs and even heavier eyeshadow, Cruise clearly relishes the opportunity to play against type even as he sends up his world's-biggest-movie-star identity, displaying a cock-of-the-rock strut that viewers haven't seen since his turn in Magnolia."[58]

Cruise starred as Jack Reacher in the film adaptation of British author Lee Child's 2005 novel One Shot. The film was released on December 21, 2012.[59] It met with positive reviews from critics and was a box office success grossing $217 million worldwide.[60][61] In 2013, he starred in the science fiction film Oblivion based on director Joseph Kosinski's graphic novel of the same name. The film met with mixed reviews and grossed $286 million worldwide. It also starred Morgan Freeman and Olga Kurylenko.[62][63] In 2014, Cruise starred in the science fiction-action film Edge of Tomorrow, which received positive reviews[64] and grossed over $370 million.[65]

In 2015, Cruise returned as Ethan Hunt in the fifth installment of the Mission: Impossible series, Mission: Impossible – Rogue Nation, which he also produced.[66] Returning cast members included Simon Pegg as Benji and Jeremy Renner as William Brandt, with Christopher McQuarrie as director. The film earned high critical acclaim[67] and was a commercial success.[68] Cruise starred in the 2017 reboot of Boris Karloff's 1932 horror movie The Mummy.[69] The new film, also titled The Mummy, received negative reviews and disappointed at the box office, though still grossed over $400m.[70][71] In 2018, Cruise again reprised Ethan Hunt, in the sixth film in his franchise, Mission: Impossible – Fallout. The film was more positively received by critics than the previous films in the series and grossed over $791 million at the box office.[72][73] Unadjusted for ticket price inflation, it was Cruise's biggest commercial success to date.[74]

2020s: Franchise films
In May 2020, it was reported that Cruise would be starring in and producing a movie shot in outer space.[75] Doug Liman would be directing, writing, and co-producing. Both will fly to the International Space Station as part of a future Axiom Space mission in a SpaceX Dragon 2 spacecraft.[76] In May 2021, Cruise protested against the Hollywood Foreign Press Association (HFPA) by returning all three of his Golden Globe Awards in light of controversy surrounding the HFPA,[77] particularly its lack of diversity, specifically no black members, and ethical questions related to financial benefits to some of its members.[78]

In 2022, Cruise reprised his role as Captain Pete "Maverick" Mitchell in Top Gun: Maverick, a film which he also produced. The film premiered at the Cannes Film Festival where Cruise earned an Honorary Palme d'Or.[79] The film was released to widespread critical praise, with many reviewers deeming it superior to its predecessor.[80] The film broke several box office records upon its release; earning over $1 billion, becoming the highest-grossing film of his career.[81] Cruise earned $100 million for the film, when combining ticket sales, his salary, and his cut of home entertainment rentals and streaming revenues.[82]

Cruise reprised his role as Ethan Hunt in Mission: Impossible - Dead Reckoning which was released in theaters on July 12, 2023. The film received critical acclaim, but was a box office disappointment due to the box-office and cultural phenomenon dubbed Barbenheimer, which was the same-day release of Christopher Nolan's historical epic film Oppenheimer and Greta Gerwig's fantasy comedy Barbie.[83] Peter Debruge of Variety praised Dead Reckoning for its performances, action sequences and a satisfying ending, writing, "This outing may be one-half of a two-part finale, but it gives audiences enough closure to stand on its own".[84] In February 2024, it was announced that Cruise would star in a new film directed by Alejandro G. Iñárritu. This is set to be his first film at Warner Bros. Pictures in 10 years.[85]

In 2024, he appeared in the Paris 2024 Olympics closing ceremony to promote Los Angeles 2028 Summer Olympics, by jumping from the roof of the Stade de France stadium in Paris. He took the flag from Mayor Karen Bass and athlete Simone Biles.[86]

Production
Cruise partnered with his former talent agent Paula Wagner to form Cruise/Wagner Productions in 1993,[87] and the company has since co-produced several of Cruise's films, the first being Mission: Impossible in 1996 which was also Cruise's first project as a producer. In addition, Cruise has produced films in which he does not appear in, namely The Others, Shattered Glass, Elizabethtown, Narc, Ask the Dust, and Without Limits.[88]


Cruise in 2016
Cruise is noted as having negotiated some of the most lucrative film deals in Hollywood and was described in 2005 by Hollywood economist Edward Jay Epstein as "one of the most powerful – and richest – forces in Hollywood." Epstein argues that Cruise is one of the few producers (the others being George Lucas, Steven Spielberg and Jerry Bruckheimer) who are regarded as able to guarantee the success of a billion-dollar film franchise. Epstein also contends that the public obsession with Cruise's tabloid controversies obscures full appreciation of Cruise's exceptional commercial prowess.[89]

Break with Paramount
On August 22, 2006, Paramount Pictures announced it was ending its 14-year relationship with Cruise. In The Wall Street Journal, chairman of Viacom (Paramount's parent company) Sumner Redstone cited the economic damage to Cruise's value as an actor and producer from his controversial public behavior and views.[90][91] Cruise/Wagner Productions responded that Paramount's announcement was a face-saving move after the production company had successfully sought alternative financing from private equity firms.[92] Industry analysts such as Edward Jay Epstein commented that the real reason for the split was most likely Paramount's discontent over Cruise/Wagner's exceptionally large share of DVD sales from the Mission: Impossible franchise.[93][94]

Management of United Artists
In November 2006, Cruise and Paula Wagner announced that they had taken over the film studio United Artists.[87] Cruise acts as a producer and star in films for United Artists, while Wagner serves as UA's chief executive. Production began in 2007 of Valkyrie, a thriller based on the July 20, 1944, assassination attempt against Adolf Hitler. The film was acquired in March 2007 by United Artists. On March 21, 2007, Cruise signed to play Claus von Stauffenberg, the protagonist. This project marked the second production to be greenlighted since Cruise and Wagner took control of United Artists. The first was its inaugural film, Lions for Lambs, directed by Robert Redford and starring Redford, Meryl Streep and Cruise. In August 2008, Wagner stepped down from her position at United Artists; she retained her stake in UA, which combined with Cruise's share amounted to 30 percent of the studio.[95] This resignation dissolved the longtime partnership between Cruise and Wagner, and by this point Cruise has mostly run of his future film productions under the name TC Productions.[citation needed]

Return to Paramount
Cruise began working with Paramount again as a producer and star with Mission: Impossible – Ghost Protocol, without Wagner, which was a critical and commercial success. He and Wagner would collaborate for the final time on the modestly successful Jack Reacher series, also for Paramount.[96]

Move to Warner Bros. Discovery
In January 2024, it was announced that his production company was forming a new strategic partnership with Warner Bros. Discovery to develop and produce original and franchise films.[97][98]

Acting credits and accolades
See also: Tom Cruise filmography and List of awards and nominations received by Tom Cruise

Cruise's star on the Hollywood Walk of Fame

Cruise's handprints in Leicester Square, London
In 2006, Premiere ranked Cruise as Hollywood's most powerful actor,[99] as Cruise came in at number 13 on the magazine's 2006 Power List, being the highest ranked actor.[100] The same year, Forbes magazine ranked him as the world's most powerful celebrity.[101] The founder of CinemaScore in 2016 cited Cruise and Leonardo DiCaprio as the "two stars, it doesn't matter how bad the film is, they can pull [the box office] up."[102][103] October 10, 2006, was declared "Tom Cruise Day" in Japan; the Japan Memorial Day Association said that he was awarded with a special day because of "his love for and close association with Japan."[104]

While reviewing Days of Thunder, film critic Roger Ebert noted the similarities between several of Cruise's 1980s films and nicknamed the formula the "Tom Cruise Picture".[105] Ebert listed nine key ingredients that make up the Tom Cruise Picture: the Cruise character, the mentor, the superior woman, the craft he must hone, the arena it takes place in, the arcana or knowledge he must learn, the trail or journey, the proto enemy, and the eventual enemy of the character. Some of Cruise's later films like A Few Good Men and The Last Samurai can also be considered to be part of this formula. Widescreenings compares two of these Cruise characters in an article on the film A Few Good Men:

[screenwriter] Aaron Sorkin interestingly takes the opposite approach of Top Gun, where Cruise also starred as the protagonist. In Top Gun, Cruise plays Mitchell who is a 'hot shot' military underachiever who makes mistakes because he is trying to outperform his late father. Where Maverick Mitchell needs to rein in the discipline, Daniel Kaffee needs to let it go, finally see what he can do.[106]

Cruise is an aerobatic pilot and was inducted as part of the Living Legends of Aviation in 2010, receiving the Aviation Inspiration and Patriotism Award from the Kiddie Hawk Air Academy. In addition to other aircraft, Cruise owns a P-51 Mustang.[107]

Personal life
Marriages and relationships
Cruise splits his time between homes in Beverly Hills, California;[108] Clearwater, Florida;[109] and the South of England, where Cruise has lived in various places such as Central London, Dulwich,[110] East Grinstead,[111] and Biggin Hill.[112] In the early-to-mid-1980s, Cruise had relationships with Melissa Gilbert,[113] Rebecca De Mornay,[114] Patti Scialfa,[115] and Cher.[116]


Cruise and Mimi Rogers at the 1989 Oscars
Cruise married actress Mimi Rogers on May 9, 1987.[117] They divorced on February 4, 1990. Rogers had grown up in Scientology and was one of its 'auditors';[118] they met when Cruise became one of her clients.[119] In a 1993 Playboy interview, Rogers discussed her split from Cruise and said that he had been considering becoming a monk, which affected their intimacy. Rogers later retracted the comments and claimed she had been misinterpreted.[120][121] Rogers received a $4 million divorce settlement.[120]

Cruise met his second wife, actress Nicole Kidman, on the set of their film Days of Thunder (1990). The couple married on December 24, 1990. They adopted two children: Isabella Jane (born 1992) and Connor Antony (born 1995). On February 5, 2001, the couple's spokesperson announced their separation.[122] Cruise filed for divorce two days later, and their marriage was dissolved later that year, with Cruise citing irreconcilable differences.[123] In a 2007 interview with Marie Claire, Kidman noted the incorrect reporting of a miscarriage early in her marriage: "It was wrongly reported as miscarriage by everyone who picked up the story. So it's huge news, and it didn't happen. I had a miscarriage at the end of my marriage, but I had an ectopic pregnancy at the beginning of my marriage."[124]

Cruise was next romantically linked with Penélope Cruz, his co-star in Vanilla Sky (2001). Their three-year relationship ended in 2004.[125] An article in the October 2012 issue of Vanity Fair stated that several sources have said that after the breakup with Cruz, Scientologist leaders launched a secret project to find Cruise a new girlfriend. According to those sources, a series of "auditions" of Scientologist actresses resulted in a short-lived relationship with Iranian-British actress Nazanin Boniadi, who subsequently left Scientology.[126] Scientology and Cruise's lawyers issued strongly worded denials and threatened to sue, accusing Vanity Fair of "shoddy journalism" and "religious bigotry".[127] Journalist Roger Friedman later reported that he received an email from director and ex-Scientologist Paul Haggis confirming the story.[128][129]


Cruise with his then-wife Katie Holmes in May 2009
In April 2005, Cruise began dating actress Katie Holmes. On April 27 that year, Cruise and Holmes—dubbed TomKat by the media—made their first public appearance together in Rome.[130] A month later, Cruise publicly declared his love for Holmes on The Oprah Winfrey Show; he jumped on Winfrey's yellow couch and stood there to make the announcement. On October 6, 2005, Cruise and Holmes announced they were expecting a child.[131] In April 2006, their daughter Suri was born.

On November 18, Holmes and Cruise were married at the 15th-century castle Castello Orsini-Odescalchi in Bracciano, in a Scientologist ceremony attended by many Hollywood stars.[132][133] Their publicists said the couple had "officialized" their marriage in Los Angeles the day before the Italian ceremony.[134] There has been widespread speculation that their marriage was arranged by the Church of Scientology.[135][136] David Miscavige, the head of Scientology, served as Cruise's best man.[137] On June 29, 2012, Holmes filed for divorce from Cruise.[138][139] On July 9, the couple signed a divorce settlement worked out by their lawyers.[140] New York law requires all divorce documents remain sealed, so the exact terms of the settlement are not publicly available.[141] Cruise stated that ex-wife Katie Holmes divorced him in part to protect the couple's daughter Suri from Scientology and that Suri is no longer a practicing member of the organization.[142]

Litigation
In 1998, Cruise successfully sued the Daily Express, a British tabloid which alleged that his marriage to Kidman was a sham designed to cover up his homosexuality.[143] In May 2001, Cruise filed a lawsuit against gay porn actor Chad Slater. Slater had told the celebrity magazine Actustar that he had been involved in an affair with Cruise. This claim was strongly denied by Cruise,[144] and Slater was ordered to pay $10 million to Cruise in damages after Slater declared he could not afford to defend himself against the suit and would therefore default. Cruise requested a default judgment, and in January 2003, a Los Angeles judge decided against Slater after he admitted that his claims were false.[145][146]

Cruise also sued Bold Magazine publisher Michael Davis for $100 million, because Davis had alleged that he had video that would prove Cruise was gay. The suit was dropped in exchange for a public statement by Davis that the video was not of Cruise, and that Cruise was heterosexual.[147] In 2006, Cruise sued cybersquatter Jeff Burgar to obtain control of the TomCruise.com domain name. When owned by Burgar, the domain redirected to information about Cruise on Celebrity1000.com. The decision to turn TomCruise.com over to Cruise was handed down by the World Intellectual Property Organization (WIPO) on July 5, 2006.[148]

In 2009, magazine editor Michael Davis Sapir[149] filed a suit charging that his phone had been wiretapped at Cruise's behest. That suit was dismissed by a Central Civil West court judge in Los Angeles on the grounds that the statute of limitations had expired on Sapir's claim.[150][151] In October 2012, Cruise filed a lawsuit against In Touch and Life & Style magazines for defamation after they claimed Cruise had "abandoned" his six-year-old daughter.[152] During deposition, Cruise admitted that "he didn't see his daughter for 110 days". The suit was settled the following year.[153]

Scientology advocacy
Cruise was converted to Scientology by his first wife, Mimi Rogers, in 1986 and became an outspoken advocate for the Church of Scientology in the 2000s. His involvement in the organization was leaked by the tabloid Star in 1990, and he publicly announced he followed Scientology in a 1992 interview with Barbara Walters. Cruise has said that Scientology, and Study Technology in particular, helped him overcome his dyslexia.[154][155] Cruise has been a close friend of Scientology leader David Miscavige since the 1980s.[156][157]

Several years after Cruise started studying Scientology, the organization's leaders promised to share some Scientology secrets with him,[158] including information about the extraterrestrial ruler Xenu. According to Janet Reitman's book Inside Scientology: The Story of America's Most Secretive Religion (2011), Cruise "freaked out" and took a step back from the Church to work on the film Eyes Wide Shut.[158] In 1999, Marty Rathbun was sent by David Miscavige to convince Cruise to return to the Church and continue his studies.[158] Cruise later sparked controversy in the 2000s with his efforts to promote Scientology.[158]

In the aftermath of 9/11, Cruise co-founded and raised donations for Downtown Medical to offer New York City rescue workers "detoxification therapy", drawing criticism from medical professionals and firefighters.[159][160] In late 2004, David Miscavige created the Scientology Freedom Medal of Valor and awarded it to Cruise for this work.[161] Former Scientologist Paul Haggis has claimed that Cruise attempted to convert several celebrities to Scientology, including James Packer, Victoria and David Beckham, Jada Pinkett, Will Smith, and Steven Spielberg.[157] Since 2008, Cruise has restricted interviewers from asking him about Scientology.[162]

Political lobbying
As well as promoting various programs to introduce people to Scientology, Cruise campaigned for Scientology to be recognized as a religion in Europe. In 2005, the Council of Paris revealed that Cruise had lobbied French Interior Minister Nicolas Sarkozy and Senate President Jean-Claude Gaudin; they described Cruise as a militant spokesman for Scientology and barred any further dealings with him.[163][164]

Controversies
Criticism of psychiatry
See also: Anti-psychiatry
In January 2004, Cruise said, "I think psychiatry should be outlawed."[165] In 2005, he criticized actress Brooke Shields for using the drug Paxil (paroxetine), an antidepressant which she used to recover from postpartum depression after the birth of her first daughter in 2003. Cruise asserted that there is no such thing as a chemical imbalance and that psychiatry is a form of pseudoscience. In response, Shields argued that Cruise "should stick to saving the world from aliens and let women who are experiencing postpartum depression decide what treatment options are best for them."[166] This led to a heated argument between Cruise and Matt Lauer on NBC's Today on June 24, 2005.[167][168]

Medical authorities view Cruise's comments as furthering the social stigma of mental illness.[169] From The Lancet, "He may be right that psychotropic drugs are overused, sometimes misused; and that lifestyle changes (and exercise for depression) can be helpful. But he is wrong, as a celebrity, to add to the burden of those with a mental illness, who often fear seeking or continuing treatment because of the stigma still attached to their condition."[169] Shields called Cruise's comments "a disservice to mothers everywhere".[170] In late August 2006, Cruise apologized in person to Shields for his comments.[171]

Scientology is well known for its opposition to mainstream psychiatry and psychoactive drugs that are routinely prescribed for treatment.[161] It was reported that Cruise's anti-psychiatry actions led to a rift with director Steven Spielberg.[172] Spielberg had reportedly mentioned in Cruise's presence the name of a doctor friend who prescribed psychiatric medication. Shortly thereafter, the doctor's office was picketed by Scientologists, reportedly angering Spielberg.[173]

YouTube video removal
Main article: Project Chanology § Tom Cruise video
On January 15, 2008, a video produced by the Church of Scientology featuring an interview with Cruise was posted on YouTube by the Anonymous-linked group Project Chanology, showing Cruise discussing what being a Scientologist means to him.[174][175] The Church of Scientology said the video had been "pirated and edited", and was taken from a three-hour video produced for members of Scientology.[175][176] YouTube removed the Cruise video from their site under threat of litigation.[177] It was subsequently reinstated on the site, and as of June 2020, the video has achieved over 15 million views.[178]

Purported influence
In March 2004, his publicist of 14 years, Pat Kingsley, resigned. Cruise's next publicist was Lee Anne DeVette, his sister, who was herself a Scientologist. She served in that role until November 2005.[179] DeVette was replaced with Paul Bloch from the publicity firm Rogers and Cowan.[180] Such restructuring was seen as a move to curtail publicity of his views on Scientology, as well as the controversy surrounding his relationship with Katie Holmes.[181] Lawrence Wright's 2013 book Going Clear: Scientology and the Prison of Belief and Alex Gibney's 2015 television documentary adaptation of the same name cast a spotlight on Cruise's role in Scientology. The book and the film both allege that the Scientology organization groomed romantic partners for Cruise and that Cruise used Sea Org and Rehabilitation Project Force workers as a source of free labor.[182][157] In the film, Cruise's former auditor Marty Rathbun claims that wife Nicole Kidman was wiretapped on Cruise's suggestion, which Cruise's lawyer denies.[183][184] Cruise's ex-girlfriend Nazanin Boniadi later compared the Scientology organization's auditioning of women to date Cruise and experiences with him to "white slavery".[185]`,
  },
];
